"""Emit build123d Python from detected segments."""
from __future__ import annotations

import textwrap

from _feature_detect import Feature2D, Segment


def _fmt_pts(pts: list[tuple[float, float]]) -> str:
    parts = [f"({x:.3f}, {y:.3f})" for x, y in pts]
    return "[" + ", ".join(parts) + "]"


def _feature_sketch_lines(f: Feature2D, indent: str) -> list[str]:
    """Lines that, inside a `with BuildSketch(...) as sk:` block, place the
    outer ring and subtract any holes."""
    lines: list[str] = []
    cx, cy = f.centroid
    locator = f"Pos({cx:.3f}, {cy:.3f})"
    if f.kind == "circle":
        lines.append(f"{indent}with Locations({locator}):")
        lines.append(f"{indent}    Circle({f.radius:.3f})")
    elif f.kind == "rectangle":
        if abs(f.rotation_deg or 0.0) < 1e-3:
            lines.append(f"{indent}with Locations({locator}):")
            lines.append(f"{indent}    Rectangle({f.width:.3f}, {f.height:.3f})")
        else:
            lines.append(
                f"{indent}with Locations(Plane.XY * "
                f"Pos({cx:.3f}, {cy:.3f}) * Rot(0, 0, {f.rotation_deg:.3f})):"
            )
            lines.append(f"{indent}    Rectangle({f.width:.3f}, {f.height:.3f})")
    else:  # polygon
        # Polygon points are absolute; pass directly. align=(Align.MIN, Align.MIN) avoids re-centering.
        lines.append(
            f"{indent}Polygon(*{_fmt_pts(f.points or [])}, align=None)"
        )
    # holes
    for h in f.holes:
        hcx, hcy = h.centroid
        hloc = f"Pos({hcx:.3f}, {hcy:.3f})"
        lines.append(f"{indent}with Locations({hloc}):")
        if h.kind == "circle":
            lines.append(f"{indent}    Circle({h.radius:.3f}, mode=Mode.SUBTRACT)")
        elif h.kind == "rectangle":
            if abs(h.rotation_deg or 0.0) < 1e-3:
                lines.append(
                    f"{indent}    Rectangle({h.width:.3f}, {h.height:.3f}, mode=Mode.SUBTRACT)"
                )
            else:
                lines.append(
                    f"{indent}    with Locations(Rot(0, 0, {h.rotation_deg:.3f})):"
                )
                lines.append(
                    f"{indent}        Rectangle({h.width:.3f}, {h.height:.3f}, mode=Mode.SUBTRACT)"
                )
        else:
            lines.append(
                f"{indent}    Polygon(*{_fmt_pts(h.points or [])}, "
                f"align=None, mode=Mode.SUBTRACT)"
            )
    return lines


def render_script(
    *,
    source_path: str,
    summary: dict,
    segments: list[Segment],
    slice_step: float,
    out_stl_path: str = "output/reconstructed.stl",
) -> str:
    header = textwrap.dedent(f'''\
        """Auto-generated by mesh2py from {source_path}.

        Original mesh:
          bbox extents : {summary["extents"][0]:.3f} x {summary["extents"][1]:.3f} x {summary["extents"][2]:.3f} mm
          volume       : {summary["volume"] if summary["volume"] is not None else "n/a"} mm^3
          triangles    : {summary["n_triangles"]}
          watertight   : {summary["is_watertight"]}

        Reconstruction strategy: extrude-stack ({len(segments)} segments at {slice_step} mm slice step).
        Edit the dimensions below to adapt the part. Each segment is a Z slab
        with its own sketch (outer rings + subtracted holes).
        """
        from build123d import (
            BuildPart, BuildSketch, Plane, Locations, Pos, Rot, Mode,
            Circle, Rectangle, Polygon, extrude, export_stl,
        )

        # --- segment list (z_lo, z_hi, height) ---
        SEGMENTS = [
    ''')
    for i, s in enumerate(segments):
        h = s.z_hi - s.z_lo
        header += f"    ({s.z_lo:.3f}, {s.z_hi:.3f}, {h:.3f}),  # seg {i}\n"
    header += "]\n\n"

    body_lines: list[str] = []
    body_lines.append("with BuildPart() as part:")
    for i, s in enumerate(segments):
        h = s.z_hi - s.z_lo
        # short feature description in a comment
        kinds = ", ".join(f.kind for f in s.rep_features) or "empty"
        body_lines.append(
            f"    # ---- segment {i}: z={s.z_lo:.3f}..{s.z_hi:.3f} "
            f"(h={h:.3f}), features=[{kinds}] ----"
        )
        if not s.rep_features:
            body_lines.append("    pass")
            continue
        body_lines.append(f"    with BuildSketch(Plane.XY.offset({s.z_lo:.3f})) as sk_{i}:")
        for f in s.rep_features:
            body_lines.extend(_feature_sketch_lines(f, indent="        "))
        body_lines.append(f"    extrude(amount={h:.3f})")
        body_lines.append("")

    body_lines.append("result = part.part")
    body_lines.append(f'export_stl(result, "{out_stl_path}")')
    body_lines.append("")
    body_lines.append("if __name__ == \"__main__\":")
    body_lines.append("    print(f\"Reconstructed bbox: {result.bounding_box()}\")")
    body_lines.append("    print(f\"Reconstructed volume: {result.volume:.3f} mm^3\")")

    return header + "\n".join(body_lines) + "\n"
