"""Emit build123d Python from detected segments."""
from __future__ import annotations

import textwrap

from _feature_detect import (
    Feature2D, Segment, LoftGroup, CylinderPrimitive, RevolvePrimitive,
)


def _fmt_pts(pts: list[tuple[float, float]]) -> str:
    parts = [f"({x:.3f}, {y:.3f})" for x, y in pts]
    return "[" + ", ".join(parts) + "]"


def _polygon_emit(pts: list[tuple[float, float]], indent: str, *,
                  mode: str | None = None) -> list[str]:
    """Emit a Polygon call that preserves absolute XY positions.

    build123d 0.10 rejects align=None in some contexts and forces a re-anchor
    when align is given. To keep the polygon at its original world position
    we:
      1. compute bbox center (cx, cy) of the absolute points
      2. translate points to be relative to that center
      3. wrap in `with Locations(Pos(cx, cy)):`
      4. use default align (Align.CENTER) which anchors at the local origin
    """
    if not pts:
        return []
    xs = [p[0] for p in pts]
    ys = [p[1] for p in pts]
    cx = (min(xs) + max(xs)) / 2.0
    cy = (min(ys) + max(ys)) / 2.0
    rel = [(x - cx, y - cy) for x, y in pts]
    mode_arg = f", mode=Mode.{mode}" if mode else ""
    return [
        f"{indent}with Locations(Pos({cx:.3f}, {cy:.3f})):",
        f"{indent}    Polygon(*{_fmt_pts(rel)}{mode_arg})",
    ]


def _feature_sketch_lines(f: Feature2D, indent: str) -> list[str]:
    """Lines that, inside a `with BuildSketch(...) as sk:` block, place the
    outer ring and subtract any holes."""
    lines: list[str] = []
    cx, cy = f.centroid
    locator = f"Pos({cx:.3f}, {cy:.3f})"
    if f.kind == "circle":
        lines.append(f"{indent}with Locations({locator}):")
        lines.append(f"{indent}    Circle({f.radius:.3f})")
    elif f.kind == "rectangle":
        if abs(f.rotation_deg or 0.0) < 1e-3:
            lines.append(f"{indent}with Locations({locator}):")
            lines.append(f"{indent}    Rectangle({f.width:.3f}, {f.height:.3f})")
        else:
            lines.append(
                f"{indent}with Locations(Plane.XY * "
                f"Pos({cx:.3f}, {cy:.3f}) * Rot(0, 0, {f.rotation_deg:.3f})):"
            )
            lines.append(f"{indent}    Rectangle({f.width:.3f}, {f.height:.3f})")
    else:  # polygon
        lines.extend(_polygon_emit(f.points or [], indent))
    # holes
    for h in f.holes:
        if h.kind == "polygon":
            # _polygon_emit emits its own `with Locations(...)`; do not wrap.
            lines.extend(_polygon_emit(h.points or [], indent, mode="SUBTRACT"))
            continue
        hcx, hcy = h.centroid
        hloc = f"Pos({hcx:.3f}, {hcy:.3f})"
        lines.append(f"{indent}with Locations({hloc}):")
        if h.kind == "circle":
            lines.append(f"{indent}    Circle({h.radius:.3f}, mode=Mode.SUBTRACT)")
        elif h.kind == "rectangle":
            if abs(h.rotation_deg or 0.0) < 1e-3:
                lines.append(
                    f"{indent}    Rectangle({h.width:.3f}, {h.height:.3f}, mode=Mode.SUBTRACT)"
                )
            else:
                lines.append(
                    f"{indent}    with Locations(Rot(0, 0, {h.rotation_deg:.3f})):"
                )
                lines.append(
                    f"{indent}        Rectangle({h.width:.3f}, {h.height:.3f}, mode=Mode.SUBTRACT)"
                )
    return lines


def render_script(
    *,
    source_path: str,
    summary: dict,
    components: list[list],   # list of (Segment | LoftGroup) per component
    slice_step: float,
    out_stl_path: str = "output/reconstructed.stl",
) -> str:
    """Emit a build123d script.

    `components` is a list of per-component segment lists. Each component
    becomes its own `BuildPart` block; all parts are bundled into a
    `Compound` so build123d only fuses topologically (fast) rather than
    booleanly (slow).
    """
    total_segs = sum(len(c) for c in components)
    n_comp = len(components)

    header = textwrap.dedent(f'''\
        """Auto-generated by mesh2py from {source_path}.

        Original mesh:
          bbox extents : {summary["extents"][0]:.3f} x {summary["extents"][1]:.3f} x {summary["extents"][2]:.3f} mm
          volume       : {summary["volume"] if summary["volume"] is not None else "n/a"} mm^3
          triangles    : {summary["n_triangles"]}
          watertight   : {summary["is_watertight"]}

        Reconstruction strategy: {n_comp} connected component(s), {total_segs} extrude segment(s)
        total at {slice_step} mm slice step. Each component is its own BuildPart;
        they are combined as a Compound at the end (no boolean fusion).
        """
        from build123d import (
            BuildPart, BuildSketch, Plane, Locations, Pos, Rot, Mode, Align, Axis,
            Circle, Rectangle, Polygon, Cylinder, Compound,
            extrude, loft, revolve, export_stl,
        )

    ''')

    body_lines: list[str] = ["parts = []", ""]

    for ci, groups in enumerate(components):
        body_lines.append(f"# ===== component {ci} ({len(groups)} ops) =====")
        body_lines.append(f"with BuildPart() as part_{ci}:")
        if not groups:
            body_lines.append("    pass")
        for si, g in enumerate(groups):
            h = g.z_hi - g.z_lo
            if isinstance(g, CylinderPrimitive):
                body_lines.append(
                    f"    # ---- comp {ci} cylinder: z={g.z_lo:.3f}..{g.z_hi:.3f} "
                    f"(h={h:.3f}, r={g.radius:.3f}) ----"
                )
                body_lines.append(
                    f"    with Locations(Pos({g.cx:.3f}, {g.cy:.3f}, {g.z_lo:.3f})):"
                )
                body_lines.append(
                    f"        Cylinder({g.radius:.3f}, {h:.3f}, "
                    f"align=(Align.CENTER, Align.CENTER, Align.MIN))"
                )
                continue
            if isinstance(g, RevolvePrimitive):
                body_lines.append(
                    f"    # ---- comp {ci} revolve: z={g.z_lo:.3f}..{g.z_hi:.3f} "
                    f"(h={h:.3f}, {len(g.profile)} profile pts) ----"
                )
                # Build closed profile in the XZ half-plane (x = radius).
                # Vertices: (0, z_lo) -> (r0, z_lo) -> ... -> (rn, z_hi) -> (0, z_hi)
                # We emit relative to the profile's bbox center and wrap in
                # Locations() so the polygon lands at its world position
                # regardless of how build123d's default Align.CENTER moves
                # the local Polygon origin.
                pts: list[tuple[float, float]] = [(0.0, g.z_lo)]
                for r, z in g.profile:
                    pts.append((float(r), float(z)))
                pts.append((0.0, g.z_hi))
                xs = [p[0] for p in pts]
                zs = [p[1] for p in pts]
                pcx = (min(xs) + max(xs)) / 2.0
                pcz = (min(zs) + max(zs)) / 2.0
                rel = [(x - pcx, z - pcz) for x, z in pts]
                pts_str = ", ".join(f"({x:.3f}, {z:.3f})" for x, z in rel)
                body_lines.append(
                    f"    with BuildSketch(Plane.XZ) as prof_{ci}_{si}:"
                )
                body_lines.append(
                    f"        with Locations(Pos({pcx:.3f}, {pcz:.3f})):"
                )
                body_lines.append(f"            Polygon({pts_str})")
                body_lines.append(
                    f"    revolve(prof_{ci}_{si}.sketch, axis=Axis.Z)"
                )
                continue
            if isinstance(g, LoftGroup):
                kinds = ", ".join(f.kind for f in g.features_lo) or "empty"
                body_lines.append(
                    f"    # ---- comp {ci} loft {si}: z={g.z_lo:.3f}..{g.z_hi:.3f} "
                    f"(h={h:.3f}, merged={g.n_merged} segs), features=[{kinds}] ----"
                )
                if not g.features_lo:
                    body_lines.append("    pass")
                    continue
                body_lines.append(
                    f"    with BuildSketch(Plane.XY.offset({g.z_lo:.3f})) "
                    f"as sk_{ci}_{si}_lo:"
                )
                for f in g.features_lo:
                    body_lines.extend(_feature_sketch_lines(f, indent="        "))
                body_lines.append(
                    f"    with BuildSketch(Plane.XY.offset({g.z_hi:.3f})) "
                    f"as sk_{ci}_{si}_hi:"
                )
                for f in g.features_hi:
                    body_lines.extend(_feature_sketch_lines(f, indent="        "))
                # Try loft; on OCCT failure, fall back to the original stack
                # of per-slice extrudes (preserves accuracy at the cost of
                # more sketches).
                body_lines.append(f"    try:")
                body_lines.append(
                    f"        loft([sk_{ci}_{si}_lo.sketch, sk_{ci}_{si}_hi.sketch])"
                )
                body_lines.append(f"    except Exception as _loft_err_{ci}_{si}:")
                body_lines.append(
                    f"        print(f'[warn] loft comp{ci} op{si} failed "
                    f"({{_loft_err_{ci}_{si}.__class__.__name__}}); falling back to stacked extrudes')"
                )
                for fbi, fb_seg in enumerate(g.segments):
                    fb_h = fb_seg.z_hi - fb_seg.z_lo
                    body_lines.append(
                        f"        with BuildSketch(Plane.XY.offset({fb_seg.z_lo:.3f})) "
                        f"as sk_{ci}_{si}_fb{fbi}:"
                    )
                    for f in fb_seg.rep_features:
                        body_lines.extend(_feature_sketch_lines(f, indent="            "))
                    body_lines.append(f"        extrude(amount={fb_h:.3f})")
            else:
                kinds = ", ".join(f.kind for f in g.rep_features) or "empty"
                body_lines.append(
                    f"    # ---- comp {ci} seg {si}: z={g.z_lo:.3f}..{g.z_hi:.3f} "
                    f"(h={h:.3f}), features=[{kinds}] ----"
                )
                if not g.rep_features:
                    body_lines.append("    pass")
                    continue
                body_lines.append(
                    f"    with BuildSketch(Plane.XY.offset({g.z_lo:.3f})) as sk_{ci}_{si}:"
                )
                for f in g.rep_features:
                    body_lines.extend(_feature_sketch_lines(f, indent="        "))
                body_lines.append(f"    extrude(amount={h:.3f})")
        # If this component contains a revolve, its axis was world Z;
        # translate the resulting part so its axis lands at (cx, cy).
        revolves = [g for g in groups if isinstance(g, RevolvePrimitive)]
        if len(revolves) == 1 and len(groups) == 1:
            r = revolves[0]
            body_lines.append(
                f"parts.append(Pos({r.cx:.3f}, {r.cy:.3f}) * part_{ci}.part)"
            )
        else:
            body_lines.append(f"parts.append(part_{ci}.part)")
        body_lines.append("")

    body_lines.append("result = Compound(parts) if len(parts) > 1 else parts[0]")
    body_lines.append(f'export_stl(result, "{out_stl_path}")')
    body_lines.append("")
    body_lines.append("if __name__ == \"__main__\":")
    body_lines.append("    print(f\"Reconstructed bbox: {result.bounding_box()}\")")
    body_lines.append("    try:")
    body_lines.append("        print(f\"Reconstructed volume: {result.volume:.3f} mm^3\")")
    body_lines.append("    except Exception:")
    body_lines.append("        pass")

    return header + "\n".join(body_lines) + "\n"
